apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:              # desired situation
  containers:
  - name: mynginx
    image: nginx
    ports:
    - containerPort: 80