apiVersion: v1
kind: Pod
metadata:
  name: forcurl
spec:
  containers:
  - name: forcurl
    image: clarusway/forping
    imagePullPolicy: IfNotPresent  #If there is an existing copy, it uses it.    Always | Never | IfNotPresent
  restartPolicy: Always
